name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-20.04"

jobs:
  - job: run_test
    strategy:
      matrix:
        python3_9:
          python.version: "3.9"
        Python3_10:
          python.version: "3.10"
        Python3_11:
          python.version: "3.11"

    timeoutInMinutes: 10

    steps:
      - task: UsePythonVersion@0
        displayName: Set python version
        inputs:
          versionSpec: "$(python.version)"
      - script: |
          install_path=`pwd`
          sudo apt-get update
          cd $install_path
          sudo env "PATH=$PATH" python -m pip install -U -r `pwd`/tests/requirements.txt
        displayName: Setup environment
      - script: python -m pytest --durations=10 -rsx -vv --cov-report=xml --cov=pysigma
        displayName: Test
      - script: python -m codecov
        displayName: Upload Coverage
